force-app/main/default/objects/Project__c/Project__c.object-meta.xml
<CustomObject>
    <label>Project</label>
    <nameField>
        <label>Project Name</label>
        <type>Text</type>
    </nameField>
    <pluralLabel>Projects</pluralLabel>
    <sharingModel>ReadWrite</sharingModel>
</CustomObject>

force-app/main/default/objects/Project__c/fields/Squad_Lead__c.field-meta.xml
<CustomField>
    <fullName>Squad_Lead__c</fullName>
    <deleteConstraint>SetNull</deleteConstraint>
    <label>Squad Lead</label>
    <referenceTo>Project_Resource__c</referenceTo>
    <relationshipLabel>Projects</relationshipLabel>
    <relationshipName>Projects</relationshipName>
    <type>Lookup</type>
</CustomField>

force-app/main/default/objects/Project__c/fields/Status__c.field-meta.xml
<CustomField>
    <fullName>Status__c</fullName>
    <label>Status</label>
    <type>Picklist</type>
    <valueSet>
        <restricted>true</restricted>
        <valueSetDefinition>
            <value>
                <fullName>Pre-Kickoff</fullName>
            </value>
            <value>
                <fullName>In Progress</fullName>
            </value>
            <value>
                <fullName>Completed</fullName>
            </value>
        </valueSetDefinition>
    </valueSet>
</CustomField>

force-app/main/default/objects/Project_Resource__c/Project_Resource__c.object-meta.xml
<CustomObject>
    <label>Project Resource</label>
    <nameField>
        <label>Project Resource Name</label>
        <type>Text</type>
    </nameField>
    <pluralLabel>Projects Resources</pluralLabel>
    <sharingModel>ControlledByParent</sharingModel>
</CustomObject>

force-app/main/default/objects/Project_Resource__c/fields/Project__c.field-meta.xml
<CustomField>
    <fullName>Project__c</fullName>
    <label>Project</label>
    <referenceTo>Project__c</referenceTo>
    <relationshipLabel>Projects Resources</relationshipLabel>
    <relationshipName>Projects_Resources</relationshipName>
    <relationshipOrder>0</relationshipOrder>
    <type>MasterDetail</type>
</CustomField>

force-app/main/default/objects/Project_Resource__c/fields/Resource__c.field-meta.xml
<CustomField>
    <fullName>Resource__c</fullName>
    <deleteConstraint>SetNull</deleteConstraint>
    <label>Resource</label>
    <referenceTo>User</referenceTo>
    <relationshipName>Projects_Resources</relationshipName>
    <type>Lookup</type>
</CustomField>

force-app/main/default/classes/SquadLeadProjectsWrapper.cls
public class SquadLeadProjectsWrapper {
	
    @AuraEnabled public List<Project__c> projects;
    @AuraEnabled public boolean hasProjects;
    
    public SquadLeadProjectsWrapper(List<Project__c> projects, boolean hasProjects){
        this.projects = projects;
        this.hasProjects = hasProjects;
    }
    
    @AuraEnabled(cacheable=true)
    public static SquadLeadProjectsWrapper getProjects(){
        
        Id userId = UserInfo.getUserId();
          //Id userId= '005Dp000000OgubIAC';
        List<Project_Resource__c> prs = [SELECT Id, Name, Resource__c, Project__c FROM Project_Resource__c WHERE Resource__c = :userId];
        
        Set<Id> projectIds = new Set<Id>();
        for(Project_Resource__c pr : prs){
            projectIds.add(pr.Project__c);
        }
        
        List<Project__c> projects = [SELECT Id, Name, Squad_Lead__c, Status__c FROM Project__c WHERE Id IN :projectIds AND Squad_Lead__c IN :prs AND Status__c = 'In Progress'];
        
        Boolean hasProjects = false;
        if(projects.size() > 0) {
            hasProjects = true;
        }
        return new SquadLeadProjectsWrapper(projects, hasProjects);
        
    }
}