force-app/main/default/objects/Project__c/Project__c.object-meta.xml
<CustomObject>
    <label>Project</label>
    <nameField>
        <label>Project Name</label>
        <type>Text</type>
    </nameField>
    <pluralLabel>Projects</pluralLabel>
    <sharingModel>ReadWrite</sharingModel>
</CustomObject>

force-app/main/default/objects/Project__c/fields/Pending_Tasks__c.field-meta.xml
<CustomField>
    <fullName>Pending_Tasks__c</fullName>
    <defaultValue>0</defaultValue>
    <label>Pending Tasks</label>
    <precision>18</precision>
    <scale>0</scale>
    <type>Number</type>
</CustomField>

force-app/main/default/objects/Project__c/fields/Status__c.field-meta.xml
<CustomField>
    <fullName>Status__c</fullName>
    <label>Status</label>
    <type>Picklist</type>
    <valueSet>
        <restricted>true</restricted>
        <valueSetDefinition>
            <value>
                <fullName>Pre-Kickoff</fullName>
            </value>
            <value>
                <fullName>In Progress</fullName>
            </value>
            <value>
                <fullName>Completed</fullName>
            </value>
        </valueSetDefinition>
    </valueSet>
</CustomField>

force-app/main/default/objects/Project_Resource__c/Project_Resource__c.object-meta.xml
<CustomObject>
    <label>Project Resource</label>
    <nameField>
        <label>Project Resource Name</label>
        <type>Text</type>
    </nameField>
    <pluralLabel>Projects Resources</pluralLabel>
    <sharingModel>ControlledByParent</sharingModel>
</CustomObject>

force-app/main/default/objects/Project_Resource__c/fields/Project__c.field-meta.xml
<CustomField>
    <fullName>Project__c</fullName>
    <label>Project</label>
    <referenceTo>Project__c</referenceTo>
    <relationshipLabel>Projects Resources</relationshipLabel>
    <relationshipName>Projects_Resources</relationshipName>
    <relationshipOrder>0</relationshipOrder>
    <type>MasterDetail</type>
</CustomField>

force-app/main/default/objects/Project_Resource__c/fields/Resource__c.field-meta.xml
<CustomField>
    <fullName>Resource__c</fullName>
    <deleteConstraint>SetNull</deleteConstraint>
    <label>Resource</label>
    <referenceTo>User</referenceTo>
    <relationshipName>Projects_Resources</relationshipName>
    <type>Lookup</type>
</CustomField>

force-app/main/default/objects/Project_Task__c/Project_Task__c.object-meta.xml
<CustomObject>
    <label>Project Task</label>
    <nameField>
        <label>Project Task Name</label>
        <type>Text</type>
    </nameField>
    <pluralLabel>Project Tasks</pluralLabel>
    <sharingModel>ReadWrite</sharingModel>
</CustomObject>

force-app/main/default/objects/Project_Task__c/fields/Estimated_Hours__c.field-meta.xml
<CustomField>
    <fullName>Estimated_Hours__c</fullName>
    <label>Estimated Hours</label>
    <precision>18</precision>
    <scale>0</scale>
    <type>Number</type>
</CustomField>

force-app/main/default/objects/Project_Task__c/fields/Project_Resource__c.field-meta.xml
<CustomField>
    <fullName>Project_Resource__c</fullName>
    <deleteConstraint>SetNull</deleteConstraint>
    <label>Project Resource</label>
    <referenceTo>Project_Resource__c</referenceTo>
    <relationshipLabel>Project Tasks</relationshipLabel>
    <relationshipName>Project_Tasks</relationshipName>
    <type>Lookup</type>
</CustomField>

force-app/main/default/objects/Project_Task__c/fields/Recorded_Hours__c.field-meta.xml
<CustomField>
    <fullName>Recorded_Hours__c</fullName>
    <defaultValue>0</defaultValue>
    <label>Recorded Hours</label>
    <precision>18</precision>
    <scale>0</scale>
    <type>Number</type>
</CustomField>

force-app/main/default/classes/TaskWrapper.cls
public class TaskWrapper {
    
    public class TaskWrapperContainer{     
        @AuraEnabled public Project__c project;
        @AuraEnabled public List<Project_Task__c> tasks;
        @AuraEnabled public Integer projectPendingTasks;
        
        public TaskWrapperContainer(Project__c project, List<Project_Task__c> tasks, Integer pendingTasks){
            this.project = project;
            this.tasks = tasks;
            this.projectPendingTasks = pendingTasks;
        }
    }
    
    // List of projects with his uncompleted tasks
    @AuraEnabled public List<TaskWrapperContainer> projectWithTasks;
    @AuraEnabled public Boolean hasTasks;
    
    public TaskWrapper(List<TaskWrapperContainer> projectWithTasks, Boolean hasTasks){
        this.projectWithTasks = projectWithTasks;
        this.hasTasks = hasTasks;
    }
    
	@AuraEnabled(cacheable=true)
    public static TaskWrapper getTaskWrapper(){
        Id userId = UserInfo.getUserId();
        
        // All my assignments to projects
        List<Project_Resource__c> projectResources = [SELECT Id, Project__c, Start_Date__c, (SELECT Id, Summary__c, Status__c, Estimated_Hours__c, Recorded_Hours__c FROM Project_Tasks__r WHERE Status__c != 'Completed' ORDER BY Status__c DESC, Summary__c ASC)
                                                      FROM Project_Resource__c
                                                      WHERE Resource__c = :userId
                                                      ORDER BY Start_Date__c];
        
        // All my assignments where I have pending tasks.
        List<Project_Resource__c> projectResourcesWithTasks = new List<Project_Resource__c>();
        for(Project_Resource__c pr : projectResources){
            if(pr.Project_Tasks__r.size() > 0){
                projectResourcesWithTasks.add(pr);
            }
        }
        
        // Ids of the projects where I'm working and I have pending tasks.
        Set<Id> projectIds = new Set<Id>();
        for(Project_Resource__c pr : projectResourcesWithTasks){
            projectIds.add(pr.Project__c);
        }
        List<Project__c> projects = [SELECT Id, Name, Pending_Tasks__c FROM Project__c WHERE Id IN :projectIds];
        
        
        // Initialize my TaskWrapperContainer list.
        List<TaskWrapperContainer> taskWrapperList = new List<TaskWrapperContainer>();
        
        
        for(Project__c project : projects){
            List<Project_Task__c> projectTasks = new List<Project_Task__c>();
            for(Project_Resource__c pr : projectResourcesWithTasks){
                if(pr.Project__c == project.Id){
                    projectTasks.addAll(pr.Project_Tasks__r);
                }
            }   
            taskWrapperList.add(new TaskWrapperContainer(project, projectTasks, projectTasks.size()));
        }
        Boolean hasTasks = false;
        if(taskWrapperList.size() > 0){
            hasTasks = true;
        }
        return new TaskWrapper(taskWrapperList, hasTasks);
    } 
}