force-app/main/default/objects/Project__c/Project__c.object-meta.xml
<CustomObject>
    <label>Project</label>
    <nameField>
        <label>Project Name</label>
        <type>Text</type>
    </nameField>
    <pluralLabel>Projects</pluralLabel>
    <sharingModel>ReadWrite</sharingModel>
</CustomObject>

force-app/main/default/objects/Project__c/fields/Squad_Lead__c.field-meta.xml
<CustomField>
    <fullName>Squad_Lead__c</fullName>
    <deleteConstraint>SetNull</deleteConstraint>
    <label>Squad Lead</label>
    <referenceTo>Project_Resource__c</referenceTo>
    <relationshipLabel>Projects</relationshipLabel>
    <relationshipName>Projects</relationshipName>
    <type>Lookup</type>
</CustomField>

force-app/main/default/objects/Project__c/fields/Status__c.field-meta.xml
<CustomField>
    <fullName>Status__c</fullName>
    <label>Status</label>
    <type>Picklist</type>
    <valueSet>
        <restricted>true</restricted>
        <valueSetDefinition>
            <value>
                <fullName>Pre-Kickoff</fullName>
            </value>
            <value>
                <fullName>In Progress</fullName>
            </value>
            <value>
                <fullName>Completed</fullName>
            </value>
        </valueSetDefinition>
    </valueSet>
</CustomField>

force-app/main/default/objects/Project_Resource__c/Project_Resource__c.object-meta.xml
<CustomObject>
    <label>Project Resource</label>
    <nameField>
        <label>Project Resource Name</label>
        <type>Text</type>
    </nameField>
    <pluralLabel>Projects Resources</pluralLabel>
    <sharingModel>ControlledByParent</sharingModel>
</CustomObject>

force-app/main/default/objects/Project_Resource__c/fields/AssignedHours__c.field-meta.xml
<CustomField>
    <fullName>AssignedHours__c</fullName>
    <label>Assigned Hours</label>
    <precision>18</precision>
    <scale>0</scale>
    <type>Number</type>
</CustomField>

force-app/main/default/objects/Project_Resource__c/fields/Project__c.field-meta.xml
<CustomField>
    <fullName>Project__c</fullName>
    <label>Project</label>
    <referenceTo>Project__c</referenceTo>
    <relationshipLabel>Projects Resources</relationshipLabel>
    <relationshipName>Projects_Resources</relationshipName>
    <relationshipOrder>0</relationshipOrder>
    <type>MasterDetail</type>
</CustomField>

force-app/main/default/objects/Project_Resource__c/fields/Resource__c.field-meta.xml
<CustomField>
    <fullName>Resource__c</fullName>
    <deleteConstraint>SetNull</deleteConstraint>
    <label>Resource</label>
    <referenceTo>User</referenceTo>
    <relationshipName>Projects_Resources</relationshipName>
    <type>Lookup</type>
</CustomField>

force-app/main/default/objects/Project_Task__c/Project_Task__c.object-meta.xml
<CustomObject>
    <label>Project Task</label>
    <nameField>
        <label>Project Task Name</label>
        <type>Text</type>
    </nameField>
    <pluralLabel>Project Tasks</pluralLabel>
    <sharingModel>ReadWrite</sharingModel>
</CustomObject>

force-app/main/default/objects/Project_Task__c/fields/Estimated_Hours__c.field-meta.xml
<CustomField>
    <fullName>Estimated_Hours__c</fullName>
    <label>Estimated Hours</label>
    <precision>18</precision>
    <scale>0</scale>
    <type>Number</type>
</CustomField>

force-app/main/default/objects/Project_Task__c/fields/Project_Resource__c.field-meta.xml
<CustomField>
    <fullName>Project_Resource__c</fullName>
    <deleteConstraint>SetNull</deleteConstraint>
    <label>Project Resource</label>
    <referenceTo>Project_Resource__c</referenceTo>
    <relationshipLabel>Project Tasks</relationshipLabel>
    <relationshipName>Project_Tasks</relationshipName>
    <type>Lookup</type>
</CustomField>

force-app/main/default/objects/Project_Task__c/fields/Recorded_Hours__c.field-meta.xml
<CustomField>
    <fullName>Recorded_Hours__c</fullName>
    <defaultValue>0</defaultValue>
    <label>Recorded Hours</label>
    <precision>18</precision>
    <scale>0</scale>
    <type>Number</type>
</CustomField>

force-app/main/default/classes/Test_TaskWrapper.cls
@isTest
public class Test_TaskWrapper {
    
    @isTest
    static void testGetTaskWrapper() {
        // Create test data
        // 
 
        User u = [SELECT Id FROM User LIMIT 1];
        
        
        Project__c p1 = new Project__c(Close_Date__c = Date.today(),
                                       Start_Date__c = Date.today().addDays(7)
                                       );
        
        insert p1;
  
        Project_Resource__c pr1 =  new Project_Resource__c(
            Project__c = p1.Id,
            Resource__c = userInfo.getUserId(),
            AssignedHours__c = 20,
            Start_Date__c = Date.today().addDays(3),
            Close_Date__c = Date.today().addDays(6)
        );
        
        insert pr1;
        
        p1.Squad_Lead__c = pr1.Id;
        p1.OwnerId = u.Id;
        update p1;
        
        Project_Task__c t1 = new Project_Task__c(Project_Resource__c= pr1.Id,
                                                 Estimated_Hours__c=10,
                                                 Recorded_Hours__c = 1,
                                                 Summary__c= 'hola',
                                                 Close_Date__c = Date.today().addDays(5),
                                                 Start_Date__c = Date.today().addDays(4),
                                                 Status__c= 'In Progress');
       
        insert t1;
        
        Project_Task__c t2 = new Project_Task__c(Project_Resource__c= pr1.Id,
                                                 Estimated_Hours__c=10,
                                                 Recorded_Hours__c =10,
                                                 Summary__c= 'hola',
                                                 Close_Date__c = Date.today().addDays(5),
                                                 Start_Date__c = Date.today().addDays(4),
                                                 Status__c = 'Completed');
        insert t2;
        
       
          
        Test.startTest();
        TaskWrapper wrapper = TaskWrapper.getTaskWrapper();
          System.debug(wrapper);
          System.debug(p1);
          System.debug(pr1);
          System.debug(t1);
          System.debug(t2);
        Test.stopTest();

        // Assert results
        
        System.assertEquals(true, wrapper.hasTasks, 'Expected to have tasks');
        System.assertEquals(1, wrapper.projectWithTasks.size(), 'Expected to have 1 projects with tasks');
      
       
    }
}