force-app/main/default/objects/Project__c/Project__c.object-meta.xml
<CustomObject>
    <label>Project</label>
    <nameField>
        <label>Project Name</label>
        <type>Text</type>
    </nameField>
    <pluralLabel>Projects</pluralLabel>
    <sharingModel>ReadWrite</sharingModel>
</CustomObject>

force-app/main/default/objects/Project__c/fields/Completed_Hours__c.field-meta.xml
<CustomField>
    <fullName>Completed_Hours__c</fullName>
    <label>Completed Hours</label>
    <summarizedField>Project_Product__c.Completed_Hours__c</summarizedField>
    <summaryForeignKey>Project_Product__c.Project__c</summaryForeignKey>
    <summaryOperation>sum</summaryOperation>
    <type>Summary</type>
</CustomField>

force-app/main/default/objects/Project_Product__c/Project_Product__c.object-meta.xml
<CustomObject>
    <label>Project Product</label>
    <nameField>
        <displayFormat>ProjectProduct-{0000}</displayFormat>
        <label>Project Product Name</label>
        <type>AutoNumber</type>
    </nameField>
    <pluralLabel>Project Products</pluralLabel>
    <sharingModel>ControlledByParent</sharingModel>
</CustomObject>

force-app/main/default/objects/Project_Product__c/fields/Completed_Hours__c.field-meta.xml
<CustomField>
    <fullName>Completed_Hours__c</fullName>
    <defaultValue>0</defaultValue>
    <label>Completed Hours</label>
    <precision>18</precision>
    <scale>0</scale>
    <type>Number</type>
</CustomField>

force-app/main/default/objects/Project_Product__c/fields/Project__c.field-meta.xml
<CustomField>
    <fullName>Project__c</fullName>
    <label>Project</label>
    <referenceTo>Project__c</referenceTo>
    <relationshipLabel>Project Products</relationshipLabel>
    <relationshipName>Project_Products</relationshipName>
    <relationshipOrder>0</relationshipOrder>
    <type>MasterDetail</type>
</CustomField>

force-app/main/default/objects/Project_Product__c/fields/Role__c.field-meta.xml
<CustomField>
    <fullName>Role__c</fullName>
    <label>Role</label>
    <type>Picklist</type>
    <valueSet>
        <restricted>true</restricted>
        <valueSetDefinition>
            <value>
                <fullName>Developer</fullName>
            </value>
            <value>
                <fullName>Consultant</fullName>
            </value>
            <value>
                <fullName>Project Manager</fullName>
            </value>
            <value>
                <fullName>Architect</fullName>
            </value>
        </valueSetDefinition>
    </valueSet>
</CustomField>

force-app/main/default/objects/Project_Resource__c/Project_Resource__c.object-meta.xml
<CustomObject>
    <label>Project Resource</label>
    <nameField>
        <label>Project Resource Name</label>
        <type>Text</type>
    </nameField>
    <pluralLabel>Projects Resources</pluralLabel>
    <sharingModel>ControlledByParent</sharingModel>
</CustomObject>

force-app/main/default/objects/Project_Resource__c/fields/AssignedHours__c.field-meta.xml
<CustomField>
    <fullName>AssignedHours__c</fullName>
    <label>Assigned Hours</label>
    <precision>18</precision>
    <scale>0</scale>
    <type>Number</type>
</CustomField>

force-app/main/default/objects/Project_Resource__c/fields/Project__c.field-meta.xml
<CustomField>
    <fullName>Project__c</fullName>
    <label>Project</label>
    <referenceTo>Project__c</referenceTo>
    <relationshipLabel>Projects Resources</relationshipLabel>
    <relationshipName>Projects_Resources</relationshipName>
    <relationshipOrder>0</relationshipOrder>
    <type>MasterDetail</type>
</CustomField>

force-app/main/default/objects/Project_Resource__c/fields/Resource__c.field-meta.xml
<CustomField>
    <fullName>Resource__c</fullName>
    <deleteConstraint>SetNull</deleteConstraint>
    <label>Resource</label>
    <referenceTo>User</referenceTo>
    <relationshipName>Projects_Resources</relationshipName>
    <type>Lookup</type>
</CustomField>

force-app/main/default/objects/Project_Resource__c/fields/Role__c.field-meta.xml
<CustomField>
    <fullName>Role__c</fullName>
    <formula>Resource__r.UserRole.Name</formula>
    <formulaTreatBlanksAs>BlankAsZero</formulaTreatBlanksAs>
    <label>Role</label>
    <type>Text</type>
</CustomField>

force-app/main/default/classes/Test_Project_Resource_Helper.cls
@isTest
public class Test_Project_Resource_Helper {
	@isTest
    private static void testOne(){
        Project__c p = new Project__c();
        p.Start_Date__c = Date.today();
        p.Close_Date__c = Date.today().addDays(40);
        insert p;
        
        Project_Product__c pp = new Project_Product__c(
        	Project__c = p.Id,
            Role__c = 'Developer',
            Quantity__c = 40
        );
        insert pp;
        
       	Project_Resource__c pr = new Project_Resource__c(
        	Project__c = p.Id,
            Resource__c = '005Dp000000OgubIAC',
            AssignedHours__c = 20,
            Start_Date__c = Date.today().addDays(2),
            Close_Date__c = Date.today().addDays(5)
        );
        test.startTest();
        	insert pr;
        test.stopTest();
        
        Project_Product__c testPP = [SELECT Id, Completed_Hours__c FROM Project_Product__c];
        System.assertEquals(20, testPP.Completed_Hours__c);
    }
    
    @isTest
    private static void testTwo(){
        Project__c p = new Project__c();
        insert p;
        
        Project_Product__c pp = new Project_Product__c(
        	Project__c = p.Id,
            Role__c = 'Developer',
            Quantity__c = 40
        );
        insert pp;
        
       	Project_Resource__c pr = new Project_Resource__c(
        	Project__c = p.Id,
            Resource__c = '005Dp000000OEChIAO',
            AssignedHours__c = 20,
            Start_Date__c = Date.today().addDays(2),
            Close_Date__c = Date.today().addDays(5)
        );
        insert pr;
        test.startTest();
          	delete pr;
        test.stopTest();
        
        Project_Product__c testPP = [SELECT Id, Completed_Hours__c FROM Project_Product__c];
        System.assertEquals(0, testPP.Completed_Hours__c);
    }
    
    @isTest
    private static void testThree(){
        Project__c p = new Project__c();
        insert p;
        
        Project_Product__c pp = new Project_Product__c(
        	Project__c = p.Id,
            Role__c = 'Developer',
            Quantity__c = 40
        );
        insert pp;
        
       	Project_Resource__c pr = new Project_Resource__c(
        	Project__c = p.Id,
            Resource__c = '005Do000001SJJHIA4',
            AssignedHours__c = 20,
            Start_Date__c = Date.today(),
            Close_Date__c = Date.today().addDays(5)
        );
        test.startTest();
            try{
        		insert pr;                
            }catch(Exception e){
                System.debug(e.getMessage());
            }

        test.stopTest();
        
        List<Project_Resource__c> testPr = [SELECT Id FROM Project_Resource__c];
        System.assertEquals(0, testPr.size());
    }
}