force-app/main/default/objects/Project__c/Project__c.object-meta.xml
<CustomObject>
    <label>Project</label>
    <nameField>
        <label>Project Name</label>
        <type>Text</type>
    </nameField>
    <pluralLabel>Projects</pluralLabel>
    <sharingModel>ReadWrite</sharingModel>
</CustomObject>

force-app/main/default/objects/Project__c/fields/Squad_Lead__c.field-meta.xml
<CustomField>
    <fullName>Squad_Lead__c</fullName>
    <deleteConstraint>SetNull</deleteConstraint>
    <label>Squad Lead</label>
    <referenceTo>Project_Resource__c</referenceTo>
    <relationshipLabel>Projects</relationshipLabel>
    <relationshipName>Projects</relationshipName>
    <type>Lookup</type>
</CustomField>

force-app/main/default/objects/Project__c/fields/Status__c.field-meta.xml
<CustomField>
    <fullName>Status__c</fullName>
    <label>Status</label>
    <type>Picklist</type>
    <valueSet>
        <restricted>true</restricted>
        <valueSetDefinition>
            <value>
                <fullName>Pre-Kickoff</fullName>
            </value>
            <value>
                <fullName>In Progress</fullName>
            </value>
            <value>
                <fullName>Completed</fullName>
            </value>
        </valueSetDefinition>
    </valueSet>
</CustomField>

force-app/main/default/objects/Project_Resource__c/Project_Resource__c.object-meta.xml
<CustomObject>
    <label>Project Resource</label>
    <nameField>
        <label>Project Resource Name</label>
        <type>Text</type>
    </nameField>
    <pluralLabel>Projects Resources</pluralLabel>
    <sharingModel>ControlledByParent</sharingModel>
</CustomObject>

force-app/main/default/objects/Project_Resource__c/fields/AssignedHours__c.field-meta.xml
<CustomField>
    <fullName>AssignedHours__c</fullName>
    <label>Assigned Hours</label>
    <precision>18</precision>
    <scale>0</scale>
    <type>Number</type>
</CustomField>

force-app/main/default/objects/Project_Resource__c/fields/Project__c.field-meta.xml
<CustomField>
    <fullName>Project__c</fullName>
    <label>Project</label>
    <referenceTo>Project__c</referenceTo>
    <relationshipLabel>Projects Resources</relationshipLabel>
    <relationshipName>Projects_Resources</relationshipName>
    <relationshipOrder>0</relationshipOrder>
    <type>MasterDetail</type>
</CustomField>

force-app/main/default/objects/Project_Resource__c/fields/Resource__c.field-meta.xml
<CustomField>
    <fullName>Resource__c</fullName>
    <deleteConstraint>SetNull</deleteConstraint>
    <label>Resource</label>
    <referenceTo>User</referenceTo>
    <relationshipName>Projects_Resources</relationshipName>
    <type>Lookup</type>
</CustomField>

force-app/main/default/classes/Test_SquadLeadProjectsWrapper.cls
@isTest
public class Test_SquadLeadProjectsWrapper {

    @isTest
    static void testgetProjects(){
        
        Id u = userinfo.getUserId();
        //Id u= '005Dp000000OgubIAC';
        Project__c p1 = new Project__c(Start_Date__c = Date.today(),
                                       Close_Date__c = Date.today().addDays(7),
                                       Status__c = 'Pre-Kickoff'
                                       );
        
        insert p1;
        
  
        Project_Resource__c pr1 =  new Project_Resource__c(
            Project__c = p1.Id,
            Resource__c = u,
            AssignedHours__c = 20,
            Start_Date__c = Date.today().addDays(3),
            Close_Date__c = Date.today().addDays(6)
        );
        
        insert pr1;
        
        p1.Squad_Lead__c = pr1.Id;
        update p1;
        p1.Status__c = 'In Progress';
        update p1;
        
        
        //List<Project_Resource__c> resources = [SELECT id, Project__c, Name, Resource__c FROM Project_Resource__c WHERE Resource__c =:u];
        //List<Project__c> projects = [SELECT id, Squad_Lead__c FROM Project__c WHERE id =:p1.Id];
        
          
        
        Test.startTest();
        SquadLeadProjectsWrapper wrapper = SquadLeadProjectsWrapper.getProjects();
        System.debug(u);
        System.debug(pr1);
        System.debug(p1);
        System.debug(wrapper);
        
        Test.stopTest();
        
        //System.assertEquals(pr1.id, wrapper.projects[0].Squad_Lead__c, 'ss');
        System.assertEquals(1, wrapper.projects.size(), 'Expected to have 1 projects');
        System.assertEquals(true, wrapper.hasProjects, 'Expected to have projects');
        

    }
}