force-app/main/default/objects/Project_Task__c/Project_Task__c.object-meta.xml
<CustomObject>
    <label>Project Task</label>
    <nameField>
        <label>Project Task Name</label>
        <type>Text</type>
    </nameField>
    <pluralLabel>Project Tasks</pluralLabel>
    <sharingModel>ReadWrite</sharingModel>
</CustomObject>

force-app/main/default/objects/Project_Task__c/fields/Estimated_Hours__c.field-meta.xml
<CustomField>
    <fullName>Estimated_Hours__c</fullName>
    <label>Estimated Hours</label>
    <precision>18</precision>
    <scale>0</scale>
    <type>Number</type>
</CustomField>

force-app/main/default/objects/Project_Task__c/fields/Recorded_Hours__c.field-meta.xml
<CustomField>
    <fullName>Recorded_Hours__c</fullName>
    <defaultValue>0</defaultValue>
    <label>Recorded Hours</label>
    <precision>18</precision>
    <scale>0</scale>
    <type>Number</type>
</CustomField>

force-app/main/default/classes/Test_ProjectTaskService.cls
@isTest
public class Test_ProjectTaskService {
    @isTest private static void testUpdateTaskStatus(){
        Project_Task__c pt = new Project_Task__c();
        pt.Status__c = 'Not Started';
        pt.Estimated_Hours__c = 5;
        pt.Recorded_Hours__c = 5;
        insert pt;
        
        Project_Task__c pt2 = new Project_Task__c();
        pt.Status__c = 'Not Started';
        pt.Estimated_Hours__c = 5;
        pt.Recorded_Hours__c = 4;
        insert pt2;
        
        Test.startTest();
        ProjectTaskService.updateTaskStatus(pt.Id, 'In Progress');
        ProjectTaskService.updateTaskStatus(pt.Id, 'Completed');
        try{
        	ProjectTaskService.updateTaskStatus(pt2.Id, 'Completed');
        }catch(Exception e){
            System.debug(e.getMessage());
        }
        Test.stopTest();
        
        List<Project_Task__c> protask = [SELECT Id FROM Project_Task__c LIMIT 1];
        System.assertEquals(1, protask.size());
    }
    
    @isTest private static void testUpdateRecordedHours(){
        Project_Task__c pt = new Project_Task__c();
        pt.Status__c = 'Not Started';
        pt.Estimated_Hours__c = 5;
        pt.Recorded_Hours__c = 5;
        insert pt;
        
        Project_Task__c pt2 = new Project_Task__c();
        pt2.Status__c = 'Not Started';
        pt2.Estimated_Hours__c = 5;
        pt2.Recorded_Hours__c = 5;
        insert pt2;
        
        Project_Task__c pt3 = new Project_Task__c();
        pt3.Status__c = 'In Progress';
        pt3.Estimated_Hours__c = 5;
        pt3.Recorded_Hours__c = 0;
        insert pt3;
        
        Test.startTest();
        ProjectTaskService.updateRecordedHours(pt3.Id, 2);
        try{
        	ProjectTaskService.updateRecordedHours(pt.Id, -1);
        }catch(Exception e){
        }
        try{
        	ProjectTaskService.updateRecordedHours(pt2.Id, 2);
        }catch(Exception e){
        }
        Test.stopTest();
        
        // Muy necesario querearlo despues de actualizarlo
        Project_Task__c protask3 = [SELECT Id, Recorded_Hours__c FROM Project_Task__c WHERE Id = :pt3.Id];
        
        System.assertEquals(5, pt.Recorded_Hours__c);
        System.assertEquals(5, pt2.Recorded_Hours__c);
        System.assertEquals(2, protask3.Recorded_Hours__c);
        
        //System.assertEquals(expected, actual)
    }
}